### ISSUE TITLE
Add support for Puzzles (AoC)

### ISSUE THREAD

**Issue by rocher** [rocher/Alice#14]
### Introduction

As a fan of the Advent of Code event, I want to share, test and compare my implementations in Ada with other users. For this, I like sharing my input files and answers to form a _test case_, so that other users can test their implementations with my test case. Also, I want to have an automatic way to test my solution with all available test cases.

> **DoD** — Users can add input files and answers (test case); users can provide a solution and test it with all available test cases.

### Tasks
- [ ] Add support for Advent of Code Puzzles similar to Project Euler CLI
- [ ] Add support for adding and sharing input files and solutions
- [ ] Provide a Puzzle checker that automatically test the implementation with all available solutions
