### ISSUE TITLE
Refactor GUI presentation

### ISSUE THREAD

**Issue by rocher** [rocher/alice#4]
### Introduction

Current GUI presentation of Project Euler Problems is a PoC. It has no complete information and element distribution on the screen must be improved.

> **DoD** — First version of Project Euler GUI with complete information of the Problem and the solution, with a pleasant look and feel.

### Tasks

- [x] Add answer visualization as text
- [ ] Add legends for graphical elements
- [x] Add more problem information: URL, difficulty ..
- [x] Check font sizes on axes and GUI in general
- [x] Fix labels on axes: display exponential notation for big numbers

**Comment by rocher** [comment]
- Add answer visualization as text
- Add legends for graphical elements
- Add more problem information: URL, difficulty ..
- Check font sizes on axes and GUI in general
